global:
  scrape_interval:     5s # Adjust based on your needs
  evaluation_interval: 5s

scrape_configs:
  - job_name: immich_api
    static_configs:
      - targets: ['ts-immich:8081']

  - job_name: immich_microservices
    static_configs:
      - targets: ['ts-immich:8082']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'promcontainer'
    static_configs:
      - targets: ['ts-immich:9002']