services:
  qbittorrent:
    container_name: qbittorrent_hotio
    hostname: qbit_hotio
    image: ghcr.io/hotio/qbittorrent
    ports:
      - 8012:8080 # Map port
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Faobu
      - WEBUI_PORTS=8080/tcp,8080/udp
      - VPN_ENABLED=true
      - VPN_CONF=wg0-fix
      - VPN_PROVIDER=proton
      - VPN_LAN_NETWORK=1.1.1.1/24
      - VPN_LAN_LEAK_ENABLED=false
      - VPN_EXPOSE_PORTS_ON_LAN
      - VPN_AUTO_PORT_FORWARD=true
      - VPN_AUTO_PORT_FORWARD_TO_PORTS=
      - VPN_KEEP_LOCAL_DNS=false
      - VPN_FIREWALL_TYPE=auto
      - VPN_HEALTHCHECK_ENABLED=false
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false
    volumes:
      - /path/to/wg-config:/config/wireguard
      - /path/to/config:/config
      - /path/to/data:/data
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    devices:
      - /dev/net/tun:/dev/net/tun
